# Generated by Django 5.0.2 on 2024-02-29 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_remove_building_latitude_remove_building_longitude'),
        ('timetables', '0002_alter_timetableopenedsection_timetable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(fields=('user', 'semester', 'order'), name='unique order for one user for one semester'),
        ),
    ]
