# Generated by Django 4.2.3 on 2023-08-09 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_meeting_remove_sectionschedule_opened_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='opened_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='courses.openedsection'),
        ),
    ]
