# Generated by Django 4.2.4 on 2023-08-24 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_meeting_opened_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='opened_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.openedsection'),
        ),
    ]
