# Generated by Django 4.2.3 on 2023-09-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_location_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='building',
            name='latitude',
            field=models.FloatField(default=38.98596, verbose_name='위도'),
        ),
        migrations.AlterField(
            model_name='building',
            name='longitude',
            field=models.FloatField(default=-76.94457, verbose_name='경도'),
        ),
        migrations.AlterField(
            model_name='building',
            name='nickname',
            field=models.CharField(max_length=127, verbose_name='Short Name'),
        ),
    ]
