# Generated by Django 4.2.5 on 2023-09-30 08:43

import apps.courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_building_full_name_alter_building_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='latitude',
            field=models.FloatField(default=apps.courses.models.Building.get_default_latitude, verbose_name='위도'),
        ),
        migrations.AlterField(
            model_name='building',
            name='longitude',
            field=models.FloatField(default=apps.courses.models.Building.get_default_longitude, verbose_name='경도'),
        ),
    ]
