# Generated by Django 4.2.5 on 2023-12-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_building_full_name_alter_building_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='notes',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisite',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='restriction',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='openedsection',
            name='holdfile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
