# Generated by Django 4.2.5 on 2024-01-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_notes_course_prerequisite_course_restriction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openedsection',
            name='holdfile',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of people on waitlist with lower priority'),
        ),
        migrations.AlterField(
            model_name='openedsection',
            name='open_seats',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of open seats currently'),
        ),
        migrations.AlterField(
            model_name='openedsection',
            name='seats',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of total seats open'),
        ),
        migrations.AlterField(
            model_name='openedsection',
            name='waitlist',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of people on waitlist with higher priority'),
        ),
    ]
