# Generated by Django 4.2.5 on 2024-01-07 11:50

from django.db import migrations, models

def populate_with_umd(apps, schema_editor):
    Institution = apps.get_model('courses', 'Institution')

    # add umd
    Institution.objects.get_or_create(full_name="University of Maryland", nickname='UMD')

class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_openedsection_holdfile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=50)),
            ],
        ),
        migrations.RunPython(populate_with_umd),
    ]
