# Generated by Django 4.2.5 on 2024-01-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_course_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='course',
            name='prerequisite',
        ),
        migrations.RemoveField(
            model_name='course',
            name='restriction',
        ),
        migrations.AddField(
            model_name='openedcourse',
            name='notes',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='openedcourse',
            name='prerequisite',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='openedcourse',
            name='restriction',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
