# Generated by Django 5.0.1 on 2024-01-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_remove_course_notes_remove_course_prerequisite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openedcourse',
            name='prerequisite',
        ),
        migrations.RemoveField(
            model_name='openedcourse',
            name='restriction',
        ),
        migrations.AlterField(
            model_name='openedcourse',
            name='notes',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
