# Generated by Django 5.0.1 on 2024-01-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_remove_openedcourse_prerequisite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='room',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
