# Generated by Django 5.0.1 on 2024-01-20 03:21

from django.db import migrations, models
from django.db.models import F

def fill_code_with_course_dash_section_code(apps, schema_editor):
    Section = apps.get_model('courses', 'Section')
    
    for s in Section.objects.all():
        course_code = s.course.course_code
        section_code = s.section_code
        
        if len(section_code) <= 4:
            s.section_code = course_code + "-" + section_code
            s.save()
        

class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_location_room'),
    ]

    operations = [
        migrations.RunPython(fill_code_with_course_dash_section_code),
    ]
