# Generated by Django 5.0.1 on 2024-01-21 14:34

import django.db.models.deletion
from django.db import migrations, models


def init_UMD_departments(apps, schema_editor):
    Department = apps.get_model("courses", "Department")
    Institution = apps.get_model("courses", "Institution")
    umd_id = Institution.objects.get(nickname="UMD").id

    from apps.scraper.scrapers import UMDScraper as us

    deps = us().get_departments_detailed(202401)
    dep_objs = [
        Department(
            institution_id=umd_id, full_name=d["full_name"], nickname=d["nickname"]
        )
        for d in deps
    ]

    Department.objects.bulk_create(dep_objs)


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0019_format_section_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("nickname", models.CharField(max_length=10, blank=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.institution",
                    ),
                ),
            ],
        ),
        migrations.RunPython(init_UMD_departments, migrations.RunPython.noop),
    ]
