# Generated by Django 5.0.2 on 2024-02-24 12:03

import django.db.models.deletion
from django.db import migrations, models


def add_institution_supported_semesters(apps, schema_editor):
    Institution = apps.get_model("courses", "Institution")
    OpenedSection = apps.get_model("courses", "OpenedSection")
    InstitutionSupportedSemester = apps.get_model(
        "courses", "InstitutionSupportedSemester"
    )

    institutions = Institution.objects.all()

    for institution in institutions:
        opened_sections = OpenedSection.objects.filter(
            section__course__institution=institution
        )
        semester_ids = opened_sections.values_list("semester", flat=True).distinct()

        for semester_id in semester_ids:
            InstitutionSupportedSemester.objects.create(
                institution=institution, semester_id=semester_id
            )


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0020_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutionSupportedSemester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.institution",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.semester",
                    ),
                ),
            ],
        ),
        migrations.RunPython(add_institution_supported_semesters),
    ]
