# Generated by Django 5.0.2 on 2024-02-28 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_institutionsupportedsemester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='building',
            name='longitude',
        ),
    ]
