# Generated by Django 5.0.2 on 2024-02-26 15:16

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_profile_image_user_profile_image_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image_file',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=False, quality=100, scale=None, size=[600, 600], upload_to='profile_images/'),
        ),
    ]
